Watching for file changes with StatReloader
"GET / HTTP/1.1" 200 1844
"GET /static/recipesapp/css/style.css HTTP/1.1" 404 1831
Not Found: /media/images/6.jpg
Not Found: /media/images/5.jpg
Not Found: /media/images/4.jpg
"GET /media/images/6.jpg HTTP/1.1" 404 3541
"GET /media/images/5.jpg HTTP/1.1" 404 3541
"GET /media/images/4.jpg HTTP/1.1" 404 3541
Watching for file changes with StatReloader
"GET / HTTP/1.1" 200 1844
"GET /static/recipesapp/css/style.css HTTP/1.1" 404 1831
Not Found: /media/images/6.jpg
Not Found: /media/images/5.jpg
"GET /media/images/6.jpg HTTP/1.1" 404 3541
Not Found: /media/images/4.jpg
"GET /media/images/5.jpg HTTP/1.1" 404 3541
"GET /media/images/4.jpg HTTP/1.1" 404 3541
Invalid HTTP_HOST header: 'plugins.jetbrains.com'. You may need to add 'plugins.jetbrains.com' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "C:\Users\dara3\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dara3\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\utils\deprecation.py", line 133, in __call__
    response = self.process_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dara3\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\middleware\common.py", line 48, in process_request
    host = request.get_host()
           ^^^^^^^^^^^^^^^^^^
  File "C:\Users\dara3\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\http\request.py", line 151, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'plugins.jetbrains.com'. You may need to add 'plugins.jetbrains.com' to ALLOWED_HOSTS.
Bad Request: /plugins.jetbrains.com:443
"CONNECT plugins.jetbrains.com:443 HTTP/1.1" 400 66836
Invalid HTTP_HOST header: 'plugins.jetbrains.com'. You may need to add 'plugins.jetbrains.com' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "C:\Users\dara3\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dara3\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\utils\deprecation.py", line 133, in __call__
    response = self.process_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dara3\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\middleware\common.py", line 48, in process_request
    host = request.get_host()
           ^^^^^^^^^^^^^^^^^^
  File "C:\Users\dara3\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\http\request.py", line 151, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'plugins.jetbrains.com'. You may need to add 'plugins.jetbrains.com' to ALLOWED_HOSTS.
Bad Request: /plugins.jetbrains.com:443
"CONNECT plugins.jetbrains.com:443 HTTP/1.1" 400 66836
Invalid HTTP_HOST header: 'plugins.jetbrains.com'. You may need to add 'plugins.jetbrains.com' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "C:\Users\dara3\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dara3\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\utils\deprecation.py", line 133, in __call__
    response = self.process_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dara3\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\middleware\common.py", line 48, in process_request
    host = request.get_host()
           ^^^^^^^^^^^^^^^^^^
  File "C:\Users\dara3\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\http\request.py", line 151, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'plugins.jetbrains.com'. You may need to add 'plugins.jetbrains.com' to ALLOWED_HOSTS.
Bad Request: /plugins.jetbrains.com:443
"CONNECT plugins.jetbrains.com:443 HTTP/1.1" 400 66836
Invalid HTTP_HOST header: 'plugins.jetbrains.com'. You may need to add 'plugins.jetbrains.com' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "C:\Users\dara3\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dara3\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\utils\deprecation.py", line 133, in __call__
    response = self.process_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dara3\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\middleware\common.py", line 48, in process_request
    host = request.get_host()
           ^^^^^^^^^^^^^^^^^^
  File "C:\Users\dara3\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\http\request.py", line 151, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'plugins.jetbrains.com'. You may need to add 'plugins.jetbrains.com' to ALLOWED_HOSTS.
Bad Request: /plugins.jetbrains.com:443
"CONNECT plugins.jetbrains.com:443 HTTP/1.1" 400 66836
Invalid HTTP_HOST header: 'plugins.jetbrains.com'. You may need to add 'plugins.jetbrains.com' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "C:\Users\dara3\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dara3\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\utils\deprecation.py", line 133, in __call__
    response = self.process_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dara3\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\middleware\common.py", line 48, in process_request
    host = request.get_host()
           ^^^^^^^^^^^^^^^^^^
  File "C:\Users\dara3\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\http\request.py", line 151, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'plugins.jetbrains.com'. You may need to add 'plugins.jetbrains.com' to ALLOWED_HOSTS.
Bad Request: /plugins.jetbrains.com:443
"CONNECT plugins.jetbrains.com:443 HTTP/1.1" 400 66836
Invalid HTTP_HOST header: 'plugins.jetbrains.com'. You may need to add 'plugins.jetbrains.com' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "C:\Users\dara3\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dara3\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\utils\deprecation.py", line 133, in __call__
    response = self.process_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dara3\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\middleware\common.py", line 48, in process_request
    host = request.get_host()
           ^^^^^^^^^^^^^^^^^^
  File "C:\Users\dara3\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\http\request.py", line 151, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'plugins.jetbrains.com'. You may need to add 'plugins.jetbrains.com' to ALLOWED_HOSTS.
Bad Request: /plugins.jetbrains.com:443
"CONNECT plugins.jetbrains.com:443 HTTP/1.1" 400 66836
Invalid HTTP_HOST header: 'plugins.jetbrains.com'. You may need to add 'plugins.jetbrains.com' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "C:\Users\dara3\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dara3\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\utils\deprecation.py", line 133, in __call__
    response = self.process_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dara3\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\middleware\common.py", line 48, in process_request
    host = request.get_host()
           ^^^^^^^^^^^^^^^^^^
  File "C:\Users\dara3\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\http\request.py", line 151, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'plugins.jetbrains.com'. You may need to add 'plugins.jetbrains.com' to ALLOWED_HOSTS.
Bad Request: /plugins.jetbrains.com:443
"CONNECT plugins.jetbrains.com:443 HTTP/1.1" 400 66836
Invalid HTTP_HOST header: 'plugins.jetbrains.com'. You may need to add 'plugins.jetbrains.com' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "C:\Users\dara3\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dara3\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\utils\deprecation.py", line 133, in __call__
    response = self.process_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dara3\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\middleware\common.py", line 48, in process_request
    host = request.get_host()
           ^^^^^^^^^^^^^^^^^^
  File "C:\Users\dara3\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\http\request.py", line 151, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'plugins.jetbrains.com'. You may need to add 'plugins.jetbrains.com' to ALLOWED_HOSTS.
Bad Request: /plugins.jetbrains.com:443
"CONNECT plugins.jetbrains.com:443 HTTP/1.1" 400 66836
Invalid HTTP_HOST header: 'plugins.jetbrains.com'. You may need to add 'plugins.jetbrains.com' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "C:\Users\dara3\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dara3\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\utils\deprecation.py", line 133, in __call__
    response = self.process_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dara3\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\middleware\common.py", line 48, in process_request
    host = request.get_host()
           ^^^^^^^^^^^^^^^^^^
  File "C:\Users\dara3\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\http\request.py", line 151, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'plugins.jetbrains.com'. You may need to add 'plugins.jetbrains.com' to ALLOWED_HOSTS.
Bad Request: /plugins.jetbrains.com:443
"CONNECT plugins.jetbrains.com:443 HTTP/1.1" 400 66836
Invalid HTTP_HOST header: 'plugins.jetbrains.com'. You may need to add 'plugins.jetbrains.com' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "C:\Users\dara3\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dara3\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\utils\deprecation.py", line 133, in __call__
    response = self.process_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dara3\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\middleware\common.py", line 48, in process_request
    host = request.get_host()
           ^^^^^^^^^^^^^^^^^^
  File "C:\Users\dara3\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\http\request.py", line 151, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'plugins.jetbrains.com'. You may need to add 'plugins.jetbrains.com' to ALLOWED_HOSTS.
Bad Request: /plugins.jetbrains.com:443
"CONNECT plugins.jetbrains.com:443 HTTP/1.1" 400 66836
Invalid HTTP_HOST header: 'plugins.jetbrains.com'. You may need to add 'plugins.jetbrains.com' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "C:\Users\dara3\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dara3\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\utils\deprecation.py", line 133, in __call__
    response = self.process_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dara3\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\middleware\common.py", line 48, in process_request
    host = request.get_host()
           ^^^^^^^^^^^^^^^^^^
  File "C:\Users\dara3\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\http\request.py", line 151, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'plugins.jetbrains.com'. You may need to add 'plugins.jetbrains.com' to ALLOWED_HOSTS.
Bad Request: /plugins.jetbrains.com:443
"CONNECT plugins.jetbrains.com:443 HTTP/1.1" 400 66836
Invalid HTTP_HOST header: 'plugins.jetbrains.com'. You may need to add 'plugins.jetbrains.com' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "C:\Users\dara3\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dara3\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\utils\deprecation.py", line 133, in __call__
    response = self.process_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dara3\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\middleware\common.py", line 48, in process_request
    host = request.get_host()
           ^^^^^^^^^^^^^^^^^^
  File "C:\Users\dara3\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\http\request.py", line 151, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'plugins.jetbrains.com'. You may need to add 'plugins.jetbrains.com' to ALLOWED_HOSTS.
Bad Request: /plugins.jetbrains.com:443
"CONNECT plugins.jetbrains.com:443 HTTP/1.1" 400 66836
Watching for file changes with StatReloader
"GET / HTTP/1.1" 200 1844
"GET /static/recipesapp/css/style.css HTTP/1.1" 404 1831
Not Found: /media/images/6.jpg
"GET /media/images/6.jpg HTTP/1.1" 404 3541
Not Found: /media/images/4.jpg
Not Found: /media/images/5.jpg
"GET /media/images/5.jpg HTTP/1.1" 404 3541
"GET /media/images/4.jpg HTTP/1.1" 404 3541
Invalid HTTP_HOST header: 'download.jetbrains.com'. You may need to add 'download.jetbrains.com' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "D:\GB\HTML CSS\FinishTask\pecipes\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "D:\GB\HTML CSS\FinishTask\pecipes\venv\Lib\site-packages\django\utils\deprecation.py", line 133, in __call__
    response = self.process_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GB\HTML CSS\FinishTask\pecipes\venv\Lib\site-packages\django\middleware\common.py", line 48, in process_request
    host = request.get_host()
           ^^^^^^^^^^^^^^^^^^
  File "D:\GB\HTML CSS\FinishTask\pecipes\venv\Lib\site-packages\django\http\request.py", line 151, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'download.jetbrains.com'. You may need to add 'download.jetbrains.com' to ALLOWED_HOSTS.
Bad Request: /download.jetbrains.com:443
"CONNECT download.jetbrains.com:443 HTTP/1.1" 400 68079
Invalid HTTP_HOST header: 'plugins.jetbrains.com'. You may need to add 'plugins.jetbrains.com' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "D:\GB\HTML CSS\FinishTask\pecipes\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "D:\GB\HTML CSS\FinishTask\pecipes\venv\Lib\site-packages\django\utils\deprecation.py", line 133, in __call__
    response = self.process_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GB\HTML CSS\FinishTask\pecipes\venv\Lib\site-packages\django\middleware\common.py", line 48, in process_request
    host = request.get_host()
           ^^^^^^^^^^^^^^^^^^
  File "D:\GB\HTML CSS\FinishTask\pecipes\venv\Lib\site-packages\django\http\request.py", line 151, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'plugins.jetbrains.com'. You may need to add 'plugins.jetbrains.com' to ALLOWED_HOSTS.
Bad Request: /plugins.jetbrains.com:443
"CONNECT plugins.jetbrains.com:443 HTTP/1.1" 400 68053
Invalid HTTP_HOST header: 'plugins.jetbrains.com'. You may need to add 'plugins.jetbrains.com' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "D:\GB\HTML CSS\FinishTask\pecipes\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "D:\GB\HTML CSS\FinishTask\pecipes\venv\Lib\site-packages\django\utils\deprecation.py", line 133, in __call__
    response = self.process_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GB\HTML CSS\FinishTask\pecipes\venv\Lib\site-packages\django\middleware\common.py", line 48, in process_request
    host = request.get_host()
           ^^^^^^^^^^^^^^^^^^
  File "D:\GB\HTML CSS\FinishTask\pecipes\venv\Lib\site-packages\django\http\request.py", line 151, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'plugins.jetbrains.com'. You may need to add 'plugins.jetbrains.com' to ALLOWED_HOSTS.
Bad Request: /plugins.jetbrains.com:443
"CONNECT plugins.jetbrains.com:443 HTTP/1.1" 400 68053
Invalid HTTP_HOST header: 'plugins.jetbrains.com'. You may need to add 'plugins.jetbrains.com' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "D:\GB\HTML CSS\FinishTask\pecipes\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "D:\GB\HTML CSS\FinishTask\pecipes\venv\Lib\site-packages\django\utils\deprecation.py", line 133, in __call__
    response = self.process_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GB\HTML CSS\FinishTask\pecipes\venv\Lib\site-packages\django\middleware\common.py", line 48, in process_request
    host = request.get_host()
           ^^^^^^^^^^^^^^^^^^
  File "D:\GB\HTML CSS\FinishTask\pecipes\venv\Lib\site-packages\django\http\request.py", line 151, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'plugins.jetbrains.com'. You may need to add 'plugins.jetbrains.com' to ALLOWED_HOSTS.
Bad Request: /plugins.jetbrains.com:443
"CONNECT plugins.jetbrains.com:443 HTTP/1.1" 400 68053
Invalid HTTP_HOST header: 'plugins.jetbrains.com'. You may need to add 'plugins.jetbrains.com' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "D:\GB\HTML CSS\FinishTask\pecipes\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "D:\GB\HTML CSS\FinishTask\pecipes\venv\Lib\site-packages\django\utils\deprecation.py", line 133, in __call__
    response = self.process_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GB\HTML CSS\FinishTask\pecipes\venv\Lib\site-packages\django\middleware\common.py", line 48, in process_request
    host = request.get_host()
           ^^^^^^^^^^^^^^^^^^
  File "D:\GB\HTML CSS\FinishTask\pecipes\venv\Lib\site-packages\django\http\request.py", line 151, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'plugins.jetbrains.com'. You may need to add 'plugins.jetbrains.com' to ALLOWED_HOSTS.
Bad Request: /plugins.jetbrains.com:443
"CONNECT plugins.jetbrains.com:443 HTTP/1.1" 400 68053
Invalid HTTP_HOST header: 'plugins.jetbrains.com'. You may need to add 'plugins.jetbrains.com' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "D:\GB\HTML CSS\FinishTask\pecipes\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "D:\GB\HTML CSS\FinishTask\pecipes\venv\Lib\site-packages\django\utils\deprecation.py", line 133, in __call__
    response = self.process_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GB\HTML CSS\FinishTask\pecipes\venv\Lib\site-packages\django\middleware\common.py", line 48, in process_request
    host = request.get_host()
           ^^^^^^^^^^^^^^^^^^
  File "D:\GB\HTML CSS\FinishTask\pecipes\venv\Lib\site-packages\django\http\request.py", line 151, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'plugins.jetbrains.com'. You may need to add 'plugins.jetbrains.com' to ALLOWED_HOSTS.
Bad Request: /plugins.jetbrains.com:443
"CONNECT plugins.jetbrains.com:443 HTTP/1.1" 400 68053
Invalid HTTP_HOST header: 'plugins.jetbrains.com'. You may need to add 'plugins.jetbrains.com' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "D:\GB\HTML CSS\FinishTask\pecipes\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "D:\GB\HTML CSS\FinishTask\pecipes\venv\Lib\site-packages\django\utils\deprecation.py", line 133, in __call__
    response = self.process_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GB\HTML CSS\FinishTask\pecipes\venv\Lib\site-packages\django\middleware\common.py", line 48, in process_request
    host = request.get_host()
           ^^^^^^^^^^^^^^^^^^
  File "D:\GB\HTML CSS\FinishTask\pecipes\venv\Lib\site-packages\django\http\request.py", line 151, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'plugins.jetbrains.com'. You may need to add 'plugins.jetbrains.com' to ALLOWED_HOSTS.
Bad Request: /plugins.jetbrains.com:443
"CONNECT plugins.jetbrains.com:443 HTTP/1.1" 400 68053
Invalid HTTP_HOST header: 'plugins.jetbrains.com'. You may need to add 'plugins.jetbrains.com' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "D:\GB\HTML CSS\FinishTask\pecipes\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "D:\GB\HTML CSS\FinishTask\pecipes\venv\Lib\site-packages\django\utils\deprecation.py", line 133, in __call__
    response = self.process_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GB\HTML CSS\FinishTask\pecipes\venv\Lib\site-packages\django\middleware\common.py", line 48, in process_request
    host = request.get_host()
           ^^^^^^^^^^^^^^^^^^
  File "D:\GB\HTML CSS\FinishTask\pecipes\venv\Lib\site-packages\django\http\request.py", line 151, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'plugins.jetbrains.com'. You may need to add 'plugins.jetbrains.com' to ALLOWED_HOSTS.
Bad Request: /plugins.jetbrains.com:443
"CONNECT plugins.jetbrains.com:443 HTTP/1.1" 400 68053
Invalid HTTP_HOST header: 'plugins.jetbrains.com'. You may need to add 'plugins.jetbrains.com' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "D:\GB\HTML CSS\FinishTask\pecipes\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "D:\GB\HTML CSS\FinishTask\pecipes\venv\Lib\site-packages\django\utils\deprecation.py", line 133, in __call__
    response = self.process_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GB\HTML CSS\FinishTask\pecipes\venv\Lib\site-packages\django\middleware\common.py", line 48, in process_request
    host = request.get_host()
           ^^^^^^^^^^^^^^^^^^
  File "D:\GB\HTML CSS\FinishTask\pecipes\venv\Lib\site-packages\django\http\request.py", line 151, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'plugins.jetbrains.com'. You may need to add 'plugins.jetbrains.com' to ALLOWED_HOSTS.
Bad Request: /plugins.jetbrains.com:443
"CONNECT plugins.jetbrains.com:443 HTTP/1.1" 400 68053
Invalid HTTP_HOST header: 'schemastore.org'. You may need to add 'schemastore.org' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "D:\GB\HTML CSS\FinishTask\pecipes\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "D:\GB\HTML CSS\FinishTask\pecipes\venv\Lib\site-packages\django\utils\deprecation.py", line 133, in __call__
    response = self.process_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GB\HTML CSS\FinishTask\pecipes\venv\Lib\site-packages\django\middleware\common.py", line 48, in process_request
    host = request.get_host()
           ^^^^^^^^^^^^^^^^^^
  File "D:\GB\HTML CSS\FinishTask\pecipes\venv\Lib\site-packages\django\http\request.py", line 151, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'schemastore.org'. You may need to add 'schemastore.org' to ALLOWED_HOSTS.
Bad Request: /schemastore.org:443
"CONNECT schemastore.org:443 HTTP/1.1" 400 67897
D:\GB\HTML CSS\FinishTask\pecipes\list_recipes\recipesapp\urls.py changed, reloading.
Watching for file changes with StatReloader
"GET / HTTP/1.1" 200 1844
"GET /static/recipesapp/css/style.css HTTP/1.1" 404 1831
"GET /media/images/4.jpg HTTP/1.1" 200 110209
"GET /media/images/6.jpg HTTP/1.1" 200 89922
"GET /media/images/5.jpg HTTP/1.1" 200 123954
"GET /recipe_show/6 HTTP/1.1" 200 4472
"GET /static/recipesapp/css/style.css HTTP/1.1" 404 1831
"GET /recipe_search/ HTTP/1.1" 200 1423
"GET /static/recipesapp/css/style.css HTTP/1.1" 404 1831
"GET /recipes_all HTTP/1.1" 200 2618
"GET /static/recipesapp/css/style.css HTTP/1.1" 404 1831
"GET /media/images/1_PzJ7go5.jpg HTTP/1.1" 200 269105
"GET /media/images/3.jpg HTTP/1.1" 200 104571
"GET /media/images/2.jpg HTTP/1.1" 200 565291
Invalid HTTP_HOST header: 'plugins.jetbrains.com'. You may need to add 'plugins.jetbrains.com' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "D:\GB\HTML CSS\FinishTask\pecipes\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "D:\GB\HTML CSS\FinishTask\pecipes\venv\Lib\site-packages\django\utils\deprecation.py", line 133, in __call__
    response = self.process_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GB\HTML CSS\FinishTask\pecipes\venv\Lib\site-packages\django\middleware\common.py", line 48, in process_request
    host = request.get_host()
           ^^^^^^^^^^^^^^^^^^
  File "D:\GB\HTML CSS\FinishTask\pecipes\venv\Lib\site-packages\django\http\request.py", line 151, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'plugins.jetbrains.com'. You may need to add 'plugins.jetbrains.com' to ALLOWED_HOSTS.
Bad Request: /plugins.jetbrains.com:443
"CONNECT plugins.jetbrains.com:443 HTTP/1.1" 400 68053
Invalid HTTP_HOST header: 'plugins.jetbrains.com'. You may need to add 'plugins.jetbrains.com' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "D:\GB\HTML CSS\FinishTask\pecipes\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "D:\GB\HTML CSS\FinishTask\pecipes\venv\Lib\site-packages\django\utils\deprecation.py", line 133, in __call__
    response = self.process_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GB\HTML CSS\FinishTask\pecipes\venv\Lib\site-packages\django\middleware\common.py", line 48, in process_request
    host = request.get_host()
           ^^^^^^^^^^^^^^^^^^
  File "D:\GB\HTML CSS\FinishTask\pecipes\venv\Lib\site-packages\django\http\request.py", line 151, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'plugins.jetbrains.com'. You may need to add 'plugins.jetbrains.com' to ALLOWED_HOSTS.
Bad Request: /plugins.jetbrains.com:443
"CONNECT plugins.jetbrains.com:443 HTTP/1.1" 400 68053
Invalid HTTP_HOST header: 'plugins.jetbrains.com'. You may need to add 'plugins.jetbrains.com' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "D:\GB\HTML CSS\FinishTask\pecipes\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "D:\GB\HTML CSS\FinishTask\pecipes\venv\Lib\site-packages\django\utils\deprecation.py", line 133, in __call__
    response = self.process_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GB\HTML CSS\FinishTask\pecipes\venv\Lib\site-packages\django\middleware\common.py", line 48, in process_request
    host = request.get_host()
           ^^^^^^^^^^^^^^^^^^
  File "D:\GB\HTML CSS\FinishTask\pecipes\venv\Lib\site-packages\django\http\request.py", line 151, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'plugins.jetbrains.com'. You may need to add 'plugins.jetbrains.com' to ALLOWED_HOSTS.
Bad Request: /plugins.jetbrains.com:443
"CONNECT plugins.jetbrains.com:443 HTTP/1.1" 400 68053
Invalid HTTP_HOST header: 'plugins.jetbrains.com'. You may need to add 'plugins.jetbrains.com' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "D:\GB\HTML CSS\FinishTask\pecipes\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "D:\GB\HTML CSS\FinishTask\pecipes\venv\Lib\site-packages\django\utils\deprecation.py", line 133, in __call__
    response = self.process_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GB\HTML CSS\FinishTask\pecipes\venv\Lib\site-packages\django\middleware\common.py", line 48, in process_request
    host = request.get_host()
           ^^^^^^^^^^^^^^^^^^
  File "D:\GB\HTML CSS\FinishTask\pecipes\venv\Lib\site-packages\django\http\request.py", line 151, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'plugins.jetbrains.com'. You may need to add 'plugins.jetbrains.com' to ALLOWED_HOSTS.
Bad Request: /plugins.jetbrains.com:443
"CONNECT plugins.jetbrains.com:443 HTTP/1.1" 400 68053
Invalid HTTP_HOST header: 'plugins.jetbrains.com'. You may need to add 'plugins.jetbrains.com' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "D:\GB\HTML CSS\FinishTask\pecipes\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "D:\GB\HTML CSS\FinishTask\pecipes\venv\Lib\site-packages\django\utils\deprecation.py", line 133, in __call__
    response = self.process_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GB\HTML CSS\FinishTask\pecipes\venv\Lib\site-packages\django\middleware\common.py", line 48, in process_request
    host = request.get_host()
           ^^^^^^^^^^^^^^^^^^
  File "D:\GB\HTML CSS\FinishTask\pecipes\venv\Lib\site-packages\django\http\request.py", line 151, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'plugins.jetbrains.com'. You may need to add 'plugins.jetbrains.com' to ALLOWED_HOSTS.
Bad Request: /plugins.jetbrains.com:443
"CONNECT plugins.jetbrains.com:443 HTTP/1.1" 400 68053
Invalid HTTP_HOST header: 'plugins.jetbrains.com'. You may need to add 'plugins.jetbrains.com' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "D:\GB\HTML CSS\FinishTask\pecipes\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "D:\GB\HTML CSS\FinishTask\pecipes\venv\Lib\site-packages\django\utils\deprecation.py", line 133, in __call__
    response = self.process_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GB\HTML CSS\FinishTask\pecipes\venv\Lib\site-packages\django\middleware\common.py", line 48, in process_request
    host = request.get_host()
           ^^^^^^^^^^^^^^^^^^
  File "D:\GB\HTML CSS\FinishTask\pecipes\venv\Lib\site-packages\django\http\request.py", line 151, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'plugins.jetbrains.com'. You may need to add 'plugins.jetbrains.com' to ALLOWED_HOSTS.
Bad Request: /plugins.jetbrains.com:443
"CONNECT plugins.jetbrains.com:443 HTTP/1.1" 400 68053
D:\GB\HTML CSS\FinishTask\pecipes\list_recipes\list_recipes\settings.py changed, reloading.
Watching for file changes with StatReloader
"GET / HTTP/1.1" 200 1844
"GET /static/recipesapp/css/style.css HTTP/1.1" 404 1831
"GET /recipe_show/6 HTTP/1.1" 200 4473
"GET /static/recipesapp/css/style.css HTTP/1.1" 404 1831
D:\GB\HTML CSS\FinishTask\pecipes\list_recipes\recipesapp\urls.py changed, reloading.
Watching for file changes with StatReloader
"GET / HTTP/1.1" 200 1844
"GET /static/recipesapp/css/style.css HTTP/1.1" 404 1831
"GET /recipe_show/5 HTTP/1.1" 200 2973
"GET /static/recipesapp/css/style.css HTTP/1.1" 404 1831
"GET /recipe_search/ HTTP/1.1" 200 1423
"GET /static/recipesapp/css/style.css HTTP/1.1" 404 1831
"GET /recipes_all HTTP/1.1" 200 2618
"GET /static/recipesapp/css/style.css HTTP/1.1" 404 1831
"GET /recipe_show/6 HTTP/1.1" 200 4473
"GET /static/recipesapp/css/style.css HTTP/1.1" 404 1831
"GET /recipes_all HTTP/1.1" 200 2618
"GET /static/recipesapp/css/style.css HTTP/1.1" 404 1831
D:\GB\HTML CSS\FinishTask\pecipes\list_recipes\recipesapp\urls.py changed, reloading.
Watching for file changes with StatReloader
"GET / HTTP/1.1" 200 1844
"GET /static/recipesapp/css/style.css HTTP/1.1" 404 1831
"GET /recipes_all HTTP/1.1" 200 2618
"GET /static/recipesapp/css/style.css HTTP/1.1" 404 1831
"GET / HTTP/1.1" 200 1844
"GET /static/recipesapp/css/style.css HTTP/1.1" 404 1831
"GET /recipe_show/4 HTTP/1.1" 200 4269
"GET /static/recipesapp/css/style.css HTTP/1.1" 404 1831
"GET /recipes_all HTTP/1.1" 200 2618
"GET /static/recipesapp/css/style.css HTTP/1.1" 404 1831
"GET / HTTP/1.1" 200 1844
"GET /static/recipesapp/css/style.css HTTP/1.1" 404 1831
Invalid HTTP_HOST header: 'download.jetbrains.com'. You may need to add 'download.jetbrains.com' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "D:\GB\HTML CSS\FinishTask\pecipes\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "D:\GB\HTML CSS\FinishTask\pecipes\venv\Lib\site-packages\django\utils\deprecation.py", line 133, in __call__
    response = self.process_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GB\HTML CSS\FinishTask\pecipes\venv\Lib\site-packages\django\middleware\common.py", line 48, in process_request
    host = request.get_host()
           ^^^^^^^^^^^^^^^^^^
  File "D:\GB\HTML CSS\FinishTask\pecipes\venv\Lib\site-packages\django\http\request.py", line 151, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'download.jetbrains.com'. You may need to add 'download.jetbrains.com' to ALLOWED_HOSTS.
Bad Request: /download.jetbrains.com:443
"CONNECT download.jetbrains.com:443 HTTP/1.1" 400 68086
Invalid HTTP_HOST header: 'www.jetbrains.com:443'. You may need to add 'www.jetbrains.com' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "D:\GB\HTML CSS\FinishTask\pecipes\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "D:\GB\HTML CSS\FinishTask\pecipes\venv\Lib\site-packages\django\utils\deprecation.py", line 133, in __call__
    response = self.process_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GB\HTML CSS\FinishTask\pecipes\venv\Lib\site-packages\django\middleware\common.py", line 48, in process_request
    host = request.get_host()
           ^^^^^^^^^^^^^^^^^^
  File "D:\GB\HTML CSS\FinishTask\pecipes\venv\Lib\site-packages\django\http\request.py", line 151, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'www.jetbrains.com:443'. You may need to add 'www.jetbrains.com' to ALLOWED_HOSTS.
Bad Request: /www.jetbrains.com:443
"CONNECT www.jetbrains.com:443 HTTP/1.1" 400 67524
"GET /recipe_search/ HTTP/1.1" 200 1423
"GET /static/recipesapp/css/style.css HTTP/1.1" 404 1831
"GET /recipes_all HTTP/1.1" 200 2618
"GET /static/recipesapp/css/style.css HTTP/1.1" 404 1831
Not Found: /media/images/2.jpg
Not Found: /media/images/1_PzJ7go5.jpg
"GET /media/images/2.jpg HTTP/1.1" 404 3541
Not Found: /media/images/3.jpg
"GET /media/images/1_PzJ7go5.jpg HTTP/1.1" 404 3565
Not Found: /media/images/6.jpg
"GET /media/images/3.jpg HTTP/1.1" 404 3541
Not Found: /media/images/5.jpg
Not Found: /media/images/4.jpg
"GET /media/images/6.jpg HTTP/1.1" 404 3541
"GET /media/images/5.jpg HTTP/1.1" 404 3541
"GET /media/images/4.jpg HTTP/1.1" 404 3541
"GET / HTTP/1.1" 200 1844
"GET /static/recipesapp/css/style.css HTTP/1.1" 404 1831
Not Found: /media/images/6.jpg
Not Found: /media/images/4.jpg
"GET /media/images/6.jpg HTTP/1.1" 404 3541
Not Found: /media/images/5.jpg
"GET /media/images/4.jpg HTTP/1.1" 404 3541
"GET /media/images/5.jpg HTTP/1.1" 404 3541
Watching for file changes with StatReloader
"GET / HTTP/1.1" 200 1844
"GET /static/recipesapp/css/style.css HTTP/1.1" 404 1831
Not Found: /media/images/6.jpg
"GET /media/images/6.jpg HTTP/1.1" 404 3541
Not Found: /media/images/5.jpg
Not Found: /media/images/4.jpg
"GET /media/images/5.jpg HTTP/1.1" 404 3541
"GET /media/images/4.jpg HTTP/1.1" 404 3541
D:\GB\HTML CSS\FinishTask\pecipes\list_recipes\recipesapp\urls.py changed, reloading.
Watching for file changes with StatReloader
"GET / HTTP/1.1" 200 1844
Not Found: /media/images/6.jpg
"GET /static/recipesapp/css/style.css HTTP/1.1" 404 1831
"GET /media/images/6.jpg HTTP/1.1" 404 3947
Not Found: /media/images/5.jpg
Not Found: /media/images/4.jpg
"GET /media/images/4.jpg HTTP/1.1" 404 3947
"GET /media/images/5.jpg HTTP/1.1" 404 3947
Watching for file changes with StatReloader
"GET / HTTP/1.1" 200 1844
"GET /static/recipesapp/css/style.css HTTP/1.1" 404 1831
Not Found: /media/images/6.jpg
Not Found: /media/images/5.jpg
Not Found: /media/images/4.jpg
"GET /media/images/6.jpg HTTP/1.1" 404 3947
"GET /media/images/5.jpg HTTP/1.1" 404 3947
"GET /media/images/4.jpg HTTP/1.1" 404 3947
"GET /recipes_all HTTP/1.1" 200 2618
"GET /static/recipesapp/css/style.css HTTP/1.1" 404 1831
Not Found: /media/images/1_PzJ7go5.jpg
"GET /media/images/1_PzJ7go5.jpg HTTP/1.1" 404 3979
Not Found: /media/images/2.jpg
"GET /media/images/2.jpg HTTP/1.1" 404 3947
Not Found: /media/images/3.jpg
Not Found: /media/images/4.jpg
Not Found: /media/images/5.jpg
"GET /media/images/3.jpg HTTP/1.1" 404 3947
"GET /media/images/4.jpg HTTP/1.1" 404 3947
Not Found: /media/images/6.jpg
"GET /media/images/5.jpg HTTP/1.1" 404 3947
"GET /media/images/6.jpg HTTP/1.1" 404 3947
"GET /recipe_search/ HTTP/1.1" 200 1423
"GET /static/recipesapp/css/style.css HTTP/1.1" 404 1831
Invalid HTTP_HOST header: 'plugins.jetbrains.com'. You may need to add 'plugins.jetbrains.com' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "D:\GB\HTML CSS\FinishTask\pecipes\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "D:\GB\HTML CSS\FinishTask\pecipes\venv\Lib\site-packages\django\utils\deprecation.py", line 133, in __call__
    response = self.process_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GB\HTML CSS\FinishTask\pecipes\venv\Lib\site-packages\django\middleware\common.py", line 48, in process_request
    host = request.get_host()
           ^^^^^^^^^^^^^^^^^^
  File "D:\GB\HTML CSS\FinishTask\pecipes\venv\Lib\site-packages\django\http\request.py", line 151, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'plugins.jetbrains.com'. You may need to add 'plugins.jetbrains.com' to ALLOWED_HOSTS.
Bad Request: /plugins.jetbrains.com:443
"CONNECT plugins.jetbrains.com:443 HTTP/1.1" 400 68060
Invalid HTTP_HOST header: 'plugins.jetbrains.com'. You may need to add 'plugins.jetbrains.com' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "D:\GB\HTML CSS\FinishTask\pecipes\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "D:\GB\HTML CSS\FinishTask\pecipes\venv\Lib\site-packages\django\utils\deprecation.py", line 133, in __call__
    response = self.process_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GB\HTML CSS\FinishTask\pecipes\venv\Lib\site-packages\django\middleware\common.py", line 48, in process_request
    host = request.get_host()
           ^^^^^^^^^^^^^^^^^^
  File "D:\GB\HTML CSS\FinishTask\pecipes\venv\Lib\site-packages\django\http\request.py", line 151, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'plugins.jetbrains.com'. You may need to add 'plugins.jetbrains.com' to ALLOWED_HOSTS.
Bad Request: /plugins.jetbrains.com:443
"CONNECT plugins.jetbrains.com:443 HTTP/1.1" 400 68060
Invalid HTTP_HOST header: 'plugins.jetbrains.com'. You may need to add 'plugins.jetbrains.com' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "D:\GB\HTML CSS\FinishTask\pecipes\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "D:\GB\HTML CSS\FinishTask\pecipes\venv\Lib\site-packages\django\utils\deprecation.py", line 133, in __call__
    response = self.process_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GB\HTML CSS\FinishTask\pecipes\venv\Lib\site-packages\django\middleware\common.py", line 48, in process_request
    host = request.get_host()
           ^^^^^^^^^^^^^^^^^^
  File "D:\GB\HTML CSS\FinishTask\pecipes\venv\Lib\site-packages\django\http\request.py", line 151, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'plugins.jetbrains.com'. You may need to add 'plugins.jetbrains.com' to ALLOWED_HOSTS.
Bad Request: /plugins.jetbrains.com:443
"CONNECT plugins.jetbrains.com:443 HTTP/1.1" 400 68060
Invalid HTTP_HOST header: 'plugins.jetbrains.com'. You may need to add 'plugins.jetbrains.com' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "D:\GB\HTML CSS\FinishTask\pecipes\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "D:\GB\HTML CSS\FinishTask\pecipes\venv\Lib\site-packages\django\utils\deprecation.py", line 133, in __call__
    response = self.process_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GB\HTML CSS\FinishTask\pecipes\venv\Lib\site-packages\django\middleware\common.py", line 48, in process_request
    host = request.get_host()
           ^^^^^^^^^^^^^^^^^^
  File "D:\GB\HTML CSS\FinishTask\pecipes\venv\Lib\site-packages\django\http\request.py", line 151, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'plugins.jetbrains.com'. You may need to add 'plugins.jetbrains.com' to ALLOWED_HOSTS.
Bad Request: /plugins.jetbrains.com:443
"CONNECT plugins.jetbrains.com:443 HTTP/1.1" 400 68060
Watching for file changes with StatReloader
"GET / HTTP/1.1" 200 1844
"GET /static/recipesapp/css/style.css HTTP/1.1" 404 1831
Not Found: /media/images/4.jpg
Not Found: /media/images/5.jpg
Not Found: /media/images/6.jpg
"GET /media/images/4.jpg HTTP/1.1" 404 3947
"GET /media/images/5.jpg HTTP/1.1" 404 3947
"GET /media/images/6.jpg HTTP/1.1" 404 3947
"GET /recipes_all HTTP/1.1" 200 2618
"GET /static/recipesapp/css/style.css HTTP/1.1" 404 1831
Not Found: /media/images/2.jpg
Not Found: /media/images/1_PzJ7go5.jpg
"GET /media/images/2.jpg HTTP/1.1" 404 3947
"GET /media/images/1_PzJ7go5.jpg HTTP/1.1" 404 3979
Not Found: /media/images/3.jpg
Not Found: /media/images/5.jpg
Not Found: /media/images/4.jpg
"GET /media/images/3.jpg HTTP/1.1" 404 3947
Not Found: /media/images/6.jpg
"GET /media/images/5.jpg HTTP/1.1" 404 3947
"GET /media/images/4.jpg HTTP/1.1" 404 3947
"GET /media/images/6.jpg HTTP/1.1" 404 3947
Invalid HTTP_HOST header: 'plugins.jetbrains.com'. You may need to add 'plugins.jetbrains.com' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "D:\GB\HTML CSS\FinishTask\pecipes\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "D:\GB\HTML CSS\FinishTask\pecipes\venv\Lib\site-packages\django\utils\deprecation.py", line 133, in __call__
    response = self.process_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GB\HTML CSS\FinishTask\pecipes\venv\Lib\site-packages\django\middleware\common.py", line 48, in process_request
    host = request.get_host()
           ^^^^^^^^^^^^^^^^^^
  File "D:\GB\HTML CSS\FinishTask\pecipes\venv\Lib\site-packages\django\http\request.py", line 151, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'plugins.jetbrains.com'. You may need to add 'plugins.jetbrains.com' to ALLOWED_HOSTS.
Bad Request: /plugins.jetbrains.com:443
"CONNECT plugins.jetbrains.com:443 HTTP/1.1" 400 68060
Invalid HTTP_HOST header: 'plugins.jetbrains.com'. You may need to add 'plugins.jetbrains.com' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "D:\GB\HTML CSS\FinishTask\pecipes\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "D:\GB\HTML CSS\FinishTask\pecipes\venv\Lib\site-packages\django\utils\deprecation.py", line 133, in __call__
    response = self.process_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GB\HTML CSS\FinishTask\pecipes\venv\Lib\site-packages\django\middleware\common.py", line 48, in process_request
    host = request.get_host()
           ^^^^^^^^^^^^^^^^^^
  File "D:\GB\HTML CSS\FinishTask\pecipes\venv\Lib\site-packages\django\http\request.py", line 151, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'plugins.jetbrains.com'. You may need to add 'plugins.jetbrains.com' to ALLOWED_HOSTS.
Bad Request: /plugins.jetbrains.com:443
"CONNECT plugins.jetbrains.com:443 HTTP/1.1" 400 68060
Invalid HTTP_HOST header: 'plugins.jetbrains.com'. You may need to add 'plugins.jetbrains.com' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "D:\GB\HTML CSS\FinishTask\pecipes\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "D:\GB\HTML CSS\FinishTask\pecipes\venv\Lib\site-packages\django\utils\deprecation.py", line 133, in __call__
    response = self.process_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GB\HTML CSS\FinishTask\pecipes\venv\Lib\site-packages\django\middleware\common.py", line 48, in process_request
    host = request.get_host()
           ^^^^^^^^^^^^^^^^^^
  File "D:\GB\HTML CSS\FinishTask\pecipes\venv\Lib\site-packages\django\http\request.py", line 151, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'plugins.jetbrains.com'. You may need to add 'plugins.jetbrains.com' to ALLOWED_HOSTS.
Bad Request: /plugins.jetbrains.com:443
"CONNECT plugins.jetbrains.com:443 HTTP/1.1" 400 68060
Invalid HTTP_HOST header: 'plugins.jetbrains.com'. You may need to add 'plugins.jetbrains.com' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "D:\GB\HTML CSS\FinishTask\pecipes\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "D:\GB\HTML CSS\FinishTask\pecipes\venv\Lib\site-packages\django\utils\deprecation.py", line 133, in __call__
    response = self.process_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GB\HTML CSS\FinishTask\pecipes\venv\Lib\site-packages\django\middleware\common.py", line 48, in process_request
    host = request.get_host()
           ^^^^^^^^^^^^^^^^^^
  File "D:\GB\HTML CSS\FinishTask\pecipes\venv\Lib\site-packages\django\http\request.py", line 151, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'plugins.jetbrains.com'. You may need to add 'plugins.jetbrains.com' to ALLOWED_HOSTS.
Bad Request: /plugins.jetbrains.com:443
"CONNECT plugins.jetbrains.com:443 HTTP/1.1" 400 68060
Watching for file changes with StatReloader
Invalid HTTP_HOST header: 'plugins.jetbrains.com'. You may need to add 'plugins.jetbrains.com' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "C:\Users\dara3\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dara3\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\utils\deprecation.py", line 133, in __call__
    response = self.process_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dara3\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\middleware\common.py", line 48, in process_request
    host = request.get_host()
           ^^^^^^^^^^^^^^^^^^
  File "C:\Users\dara3\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\http\request.py", line 151, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'plugins.jetbrains.com'. You may need to add 'plugins.jetbrains.com' to ALLOWED_HOSTS.
Bad Request: /plugins.jetbrains.com:443
"CONNECT plugins.jetbrains.com:443 HTTP/1.1" 400 66843
Invalid HTTP_HOST header: 'plugins.jetbrains.com'. You may need to add 'plugins.jetbrains.com' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "C:\Users\dara3\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dara3\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\utils\deprecation.py", line 133, in __call__
    response = self.process_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dara3\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\middleware\common.py", line 48, in process_request
    host = request.get_host()
           ^^^^^^^^^^^^^^^^^^
  File "C:\Users\dara3\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\http\request.py", line 151, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'plugins.jetbrains.com'. You may need to add 'plugins.jetbrains.com' to ALLOWED_HOSTS.
Bad Request: /plugins.jetbrains.com:443
"CONNECT plugins.jetbrains.com:443 HTTP/1.1" 400 66843
Invalid HTTP_HOST header: 'plugins.jetbrains.com'. You may need to add 'plugins.jetbrains.com' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "C:\Users\dara3\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dara3\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\utils\deprecation.py", line 133, in __call__
    response = self.process_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dara3\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\middleware\common.py", line 48, in process_request
    host = request.get_host()
           ^^^^^^^^^^^^^^^^^^
  File "C:\Users\dara3\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\http\request.py", line 151, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'plugins.jetbrains.com'. You may need to add 'plugins.jetbrains.com' to ALLOWED_HOSTS.
Bad Request: /plugins.jetbrains.com:443
"CONNECT plugins.jetbrains.com:443 HTTP/1.1" 400 66843
Invalid HTTP_HOST header: 'plugins.jetbrains.com'. You may need to add 'plugins.jetbrains.com' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "C:\Users\dara3\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dara3\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\utils\deprecation.py", line 133, in __call__
    response = self.process_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dara3\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\middleware\common.py", line 48, in process_request
    host = request.get_host()
           ^^^^^^^^^^^^^^^^^^
  File "C:\Users\dara3\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\http\request.py", line 151, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'plugins.jetbrains.com'. You may need to add 'plugins.jetbrains.com' to ALLOWED_HOSTS.
Bad Request: /plugins.jetbrains.com:443
"CONNECT plugins.jetbrains.com:443 HTTP/1.1" 400 66843
Invalid HTTP_HOST header: 'plugins.jetbrains.com'. You may need to add 'plugins.jetbrains.com' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "C:\Users\dara3\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dara3\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\utils\deprecation.py", line 133, in __call__
    response = self.process_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dara3\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\middleware\common.py", line 48, in process_request
    host = request.get_host()
           ^^^^^^^^^^^^^^^^^^
  File "C:\Users\dara3\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\http\request.py", line 151, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'plugins.jetbrains.com'. You may need to add 'plugins.jetbrains.com' to ALLOWED_HOSTS.
"GET / HTTP/1.1" 200 1844
Bad Request: /plugins.jetbrains.com:443
"CONNECT plugins.jetbrains.com:443 HTTP/1.1" 400 66843
Invalid HTTP_HOST header: 'plugins.jetbrains.com'. You may need to add 'plugins.jetbrains.com' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "C:\Users\dara3\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dara3\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\utils\deprecation.py", line 133, in __call__
    response = self.process_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dara3\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\middleware\common.py", line 48, in process_request
    host = request.get_host()
           ^^^^^^^^^^^^^^^^^^
  File "C:\Users\dara3\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\http\request.py", line 151, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'plugins.jetbrains.com'. You may need to add 'plugins.jetbrains.com' to ALLOWED_HOSTS.
"GET /static/recipesapp/css/style.css HTTP/1.1" 404 1831
Not Found: /media/images/6.jpg
"GET /media/images/6.jpg HTTP/1.1" 404 3947
Not Found: /media/images/5.jpg
Bad Request: /plugins.jetbrains.com:443
Not Found: /media/images/4.jpg
"GET /media/images/5.jpg HTTP/1.1" 404 3947
"CONNECT plugins.jetbrains.com:443 HTTP/1.1" 400 66843
Invalid HTTP_HOST header: 'plugins.jetbrains.com'. You may need to add 'plugins.jetbrains.com' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "C:\Users\dara3\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dara3\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\utils\deprecation.py", line 133, in __call__
    response = self.process_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dara3\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\middleware\common.py", line 48, in process_request
    host = request.get_host()
           ^^^^^^^^^^^^^^^^^^
  File "C:\Users\dara3\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\http\request.py", line 151, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'plugins.jetbrains.com'. You may need to add 'plugins.jetbrains.com' to ALLOWED_HOSTS.
"GET /media/images/4.jpg HTTP/1.1" 404 3947
Bad Request: /plugins.jetbrains.com:443
"CONNECT plugins.jetbrains.com:443 HTTP/1.1" 400 66843
Invalid HTTP_HOST header: 'plugins.jetbrains.com'. You may need to add 'plugins.jetbrains.com' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "C:\Users\dara3\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dara3\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\utils\deprecation.py", line 133, in __call__
    response = self.process_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dara3\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\middleware\common.py", line 48, in process_request
    host = request.get_host()
           ^^^^^^^^^^^^^^^^^^
  File "C:\Users\dara3\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\http\request.py", line 151, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'plugins.jetbrains.com'. You may need to add 'plugins.jetbrains.com' to ALLOWED_HOSTS.
Bad Request: /plugins.jetbrains.com:443
"CONNECT plugins.jetbrains.com:443 HTTP/1.1" 400 66843
Invalid HTTP_HOST header: 'plugins.jetbrains.com'. You may need to add 'plugins.jetbrains.com' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "C:\Users\dara3\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dara3\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\utils\deprecation.py", line 133, in __call__
    response = self.process_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dara3\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\middleware\common.py", line 48, in process_request
    host = request.get_host()
           ^^^^^^^^^^^^^^^^^^
  File "C:\Users\dara3\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\http\request.py", line 151, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'plugins.jetbrains.com'. You may need to add 'plugins.jetbrains.com' to ALLOWED_HOSTS.
Bad Request: /plugins.jetbrains.com:443
"CONNECT plugins.jetbrains.com:443 HTTP/1.1" 400 66843
Invalid HTTP_HOST header: 'plugins.jetbrains.com'. You may need to add 'plugins.jetbrains.com' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "C:\Users\dara3\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dara3\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\utils\deprecation.py", line 133, in __call__
    response = self.process_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dara3\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\middleware\common.py", line 48, in process_request
    host = request.get_host()
           ^^^^^^^^^^^^^^^^^^
  File "C:\Users\dara3\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\http\request.py", line 151, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'plugins.jetbrains.com'. You may need to add 'plugins.jetbrains.com' to ALLOWED_HOSTS.
Bad Request: /plugins.jetbrains.com:443
"CONNECT plugins.jetbrains.com:443 HTTP/1.1" 400 66843
Invalid HTTP_HOST header: 'plugins.jetbrains.com'. You may need to add 'plugins.jetbrains.com' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "C:\Users\dara3\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dara3\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\utils\deprecation.py", line 133, in __call__
    response = self.process_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dara3\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\middleware\common.py", line 48, in process_request
    host = request.get_host()
           ^^^^^^^^^^^^^^^^^^
  File "C:\Users\dara3\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\http\request.py", line 151, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'plugins.jetbrains.com'. You may need to add 'plugins.jetbrains.com' to ALLOWED_HOSTS.
Bad Request: /plugins.jetbrains.com:443
"CONNECT plugins.jetbrains.com:443 HTTP/1.1" 400 66843
Invalid HTTP_HOST header: 'plugins.jetbrains.com'. You may need to add 'plugins.jetbrains.com' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "C:\Users\dara3\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dara3\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\utils\deprecation.py", line 133, in __call__
    response = self.process_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dara3\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\middleware\common.py", line 48, in process_request
    host = request.get_host()
           ^^^^^^^^^^^^^^^^^^
  File "C:\Users\dara3\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\http\request.py", line 151, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'plugins.jetbrains.com'. You may need to add 'plugins.jetbrains.com' to ALLOWED_HOSTS.
Bad Request: /plugins.jetbrains.com:443
"CONNECT plugins.jetbrains.com:443 HTTP/1.1" 400 66843
D:\GB\HTML CSS\FinishTask\pecipes\list_recipes\recipesapp\views.py changed, reloading.
Watching for file changes with StatReloader
Invalid HTTP_HOST header: 'plugins.jetbrains.com'. You may need to add 'plugins.jetbrains.com' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "C:\Users\dara3\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dara3\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\utils\deprecation.py", line 133, in __call__
    response = self.process_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dara3\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\middleware\common.py", line 48, in process_request
    host = request.get_host()
           ^^^^^^^^^^^^^^^^^^
  File "C:\Users\dara3\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\http\request.py", line 151, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'plugins.jetbrains.com'. You may need to add 'plugins.jetbrains.com' to ALLOWED_HOSTS.
Bad Request: /plugins.jetbrains.com:443
"CONNECT plugins.jetbrains.com:443 HTTP/1.1" 400 66843
Invalid HTTP_HOST header: 'plugins.jetbrains.com'. You may need to add 'plugins.jetbrains.com' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "C:\Users\dara3\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dara3\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\utils\deprecation.py", line 133, in __call__
    response = self.process_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dara3\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\middleware\common.py", line 48, in process_request
    host = request.get_host()
           ^^^^^^^^^^^^^^^^^^
  File "C:\Users\dara3\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\http\request.py", line 151, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'plugins.jetbrains.com'. You may need to add 'plugins.jetbrains.com' to ALLOWED_HOSTS.
Bad Request: /plugins.jetbrains.com:443
"CONNECT plugins.jetbrains.com:443 HTTP/1.1" 400 66843
Invalid HTTP_HOST header: 'plugins.jetbrains.com'. You may need to add 'plugins.jetbrains.com' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "C:\Users\dara3\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dara3\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\utils\deprecation.py", line 133, in __call__
    response = self.process_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dara3\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\middleware\common.py", line 48, in process_request
    host = request.get_host()
           ^^^^^^^^^^^^^^^^^^
  File "C:\Users\dara3\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\http\request.py", line 151, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'plugins.jetbrains.com'. You may need to add 'plugins.jetbrains.com' to ALLOWED_HOSTS.
Bad Request: /plugins.jetbrains.com:443
"CONNECT plugins.jetbrains.com:443 HTTP/1.1" 400 66843
Invalid HTTP_HOST header: 'plugins.jetbrains.com'. You may need to add 'plugins.jetbrains.com' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "C:\Users\dara3\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dara3\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\utils\deprecation.py", line 133, in __call__
    response = self.process_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dara3\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\middleware\common.py", line 48, in process_request
    host = request.get_host()
           ^^^^^^^^^^^^^^^^^^
  File "C:\Users\dara3\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\http\request.py", line 151, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'plugins.jetbrains.com'. You may need to add 'plugins.jetbrains.com' to ALLOWED_HOSTS.
Bad Request: /plugins.jetbrains.com:443
"CONNECT plugins.jetbrains.com:443 HTTP/1.1" 400 66843
"GET / HTTP/1.1" 200 1844
"GET /static/recipesapp/css/style.css HTTP/1.1" 404 1831
Not Found: /media/images/6.jpg
"GET /media/images/6.jpg HTTP/1.1" 404 3947
Not Found: /media/images/5.jpg
Not Found: /media/images/4.jpg
"GET /media/images/5.jpg HTTP/1.1" 404 3947
"GET /media/images/4.jpg HTTP/1.1" 404 3947
D:\GB\HTML CSS\FinishTask\pecipes\list_recipes\list_recipes\settings.py changed, reloading.
Watching for file changes with StatReloader
"GET /recipe_show/1 HTTP/1.1" 200 11397
"GET /static/recipesapp/css/style.css HTTP/1.1" 404 1831
Not Found: /media/images/1_PzJ7go5.jpg
"GET /media/images/1_PzJ7go5.jpg HTTP/1.1" 404 3979
Invalid HTTP_HOST header: 'plugins.jetbrains.com'. You may need to add 'plugins.jetbrains.com' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "C:\Users\dara3\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dara3\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\utils\deprecation.py", line 133, in __call__
    response = self.process_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dara3\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\middleware\common.py", line 48, in process_request
    host = request.get_host()
           ^^^^^^^^^^^^^^^^^^
  File "C:\Users\dara3\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\http\request.py", line 151, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'plugins.jetbrains.com'. You may need to add 'plugins.jetbrains.com' to ALLOWED_HOSTS.
Bad Request: /plugins.jetbrains.com:443
"CONNECT plugins.jetbrains.com:443 HTTP/1.1" 400 66856
Invalid HTTP_HOST header: 'plugins.jetbrains.com'. You may need to add 'plugins.jetbrains.com' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "C:\Users\dara3\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dara3\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\utils\deprecation.py", line 133, in __call__
    response = self.process_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dara3\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\middleware\common.py", line 48, in process_request
    host = request.get_host()
           ^^^^^^^^^^^^^^^^^^
  File "C:\Users\dara3\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\http\request.py", line 151, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'plugins.jetbrains.com'. You may need to add 'plugins.jetbrains.com' to ALLOWED_HOSTS.
Bad Request: /plugins.jetbrains.com:443
"CONNECT plugins.jetbrains.com:443 HTTP/1.1" 400 66856
Invalid HTTP_HOST header: 'schemastore.org'. You may need to add 'schemastore.org' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "C:\Users\dara3\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dara3\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\utils\deprecation.py", line 133, in __call__
    response = self.process_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dara3\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\middleware\common.py", line 48, in process_request
    host = request.get_host()
           ^^^^^^^^^^^^^^^^^^
  File "C:\Users\dara3\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\http\request.py", line 151, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'schemastore.org'. You may need to add 'schemastore.org' to ALLOWED_HOSTS.
Bad Request: /schemastore.org:443
"CONNECT schemastore.org:443 HTTP/1.1" 400 66700
Invalid HTTP_HOST header: 'download.jetbrains.com'. You may need to add 'download.jetbrains.com' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "C:\Users\dara3\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dara3\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\utils\deprecation.py", line 133, in __call__
    response = self.process_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dara3\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\middleware\common.py", line 48, in process_request
    host = request.get_host()
           ^^^^^^^^^^^^^^^^^^
  File "C:\Users\dara3\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\http\request.py", line 151, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'download.jetbrains.com'. You may need to add 'download.jetbrains.com' to ALLOWED_HOSTS.
Bad Request: /download.jetbrains.com:443
"CONNECT download.jetbrains.com:443 HTTP/1.1" 400 66882
Invalid HTTP_HOST header: 'plugins.jetbrains.com'. You may need to add 'plugins.jetbrains.com' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "C:\Users\dara3\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dara3\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\utils\deprecation.py", line 133, in __call__
    response = self.process_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dara3\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\middleware\common.py", line 48, in process_request
    host = request.get_host()
           ^^^^^^^^^^^^^^^^^^
  File "C:\Users\dara3\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\http\request.py", line 151, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'plugins.jetbrains.com'. You may need to add 'plugins.jetbrains.com' to ALLOWED_HOSTS.
Bad Request: /plugins.jetbrains.com:443
"CONNECT plugins.jetbrains.com:443 HTTP/1.1" 400 66856
Invalid HTTP_HOST header: 'plugins.jetbrains.com'. You may need to add 'plugins.jetbrains.com' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "C:\Users\dara3\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dara3\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\utils\deprecation.py", line 133, in __call__
    response = self.process_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dara3\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\middleware\common.py", line 48, in process_request
    host = request.get_host()
           ^^^^^^^^^^^^^^^^^^
  File "C:\Users\dara3\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\http\request.py", line 151, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'plugins.jetbrains.com'. You may need to add 'plugins.jetbrains.com' to ALLOWED_HOSTS.
Bad Request: /plugins.jetbrains.com:443
"CONNECT plugins.jetbrains.com:443 HTTP/1.1" 400 66856
Invalid HTTP_HOST header: 'plugins.jetbrains.com'. You may need to add 'plugins.jetbrains.com' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "C:\Users\dara3\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dara3\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\utils\deprecation.py", line 133, in __call__
    response = self.process_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dara3\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\middleware\common.py", line 48, in process_request
    host = request.get_host()
           ^^^^^^^^^^^^^^^^^^
  File "C:\Users\dara3\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\http\request.py", line 151, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'plugins.jetbrains.com'. You may need to add 'plugins.jetbrains.com' to ALLOWED_HOSTS.
Bad Request: /plugins.jetbrains.com:443
"CONNECT plugins.jetbrains.com:443 HTTP/1.1" 400 66856
Invalid HTTP_HOST header: 'plugins.jetbrains.com'. You may need to add 'plugins.jetbrains.com' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "C:\Users\dara3\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dara3\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\utils\deprecation.py", line 133, in __call__
    response = self.process_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dara3\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\middleware\common.py", line 48, in process_request
    host = request.get_host()
           ^^^^^^^^^^^^^^^^^^
  File "C:\Users\dara3\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\http\request.py", line 151, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'plugins.jetbrains.com'. You may need to add 'plugins.jetbrains.com' to ALLOWED_HOSTS.
Bad Request: /plugins.jetbrains.com:443
"CONNECT plugins.jetbrains.com:443 HTTP/1.1" 400 66856
D:\GB\HTML CSS\FinishTask\pecipes\list_recipes\list_recipes\settings.py changed, reloading.
Watching for file changes with StatReloader
"GET / HTTP/1.1" 200 1844
"GET /static/recipesapp/css/style.css HTTP/1.1" 404 1831
"GET /media/images/6.jpg HTTP/1.1" 200 89922
"GET /media/images/5.jpg HTTP/1.1" 200 123954
"GET /media/images/4.jpg HTTP/1.1" 200 110209
"GET /recipe_show/6 HTTP/1.1" 200 4473
"GET /static/recipesapp/css/style.css HTTP/1.1" 404 1831
"GET /recipes_all HTTP/1.1" 200 2618
"GET /static/recipesapp/css/style.css HTTP/1.1" 404 1831
"GET /media/images/1_PzJ7go5.jpg HTTP/1.1" 200 269105
"GET /media/images/3.jpg HTTP/1.1" 200 104571
"GET /media/images/2.jpg HTTP/1.1" 200 565291
"GET /recipe_search/ HTTP/1.1" 200 1423
"GET /static/recipesapp/css/style.css HTTP/1.1" 404 1831
"GET /recipe_add/ HTTP/1.1" 302 0
"GET /login/ HTTP/1.1" 200 1272
"GET /static/recipesapp/css/style.css HTTP/1.1" 404 1831
"GET /login/ HTTP/1.1" 200 1206
"GET /static/recipesapp/css/style.css HTTP/1.1" 404 1831
"GET / HTTP/1.1" 200 1844
"GET /static/recipesapp/css/style.css HTTP/1.1" 404 1831
Invalid HTTP_HOST header: 'download.jetbrains.com'. You may need to add 'download.jetbrains.com' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "C:\Users\dara3\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dara3\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\utils\deprecation.py", line 133, in __call__
    response = self.process_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dara3\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\middleware\common.py", line 48, in process_request
    host = request.get_host()
           ^^^^^^^^^^^^^^^^^^
  File "C:\Users\dara3\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\http\request.py", line 151, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'download.jetbrains.com'. You may need to add 'download.jetbrains.com' to ALLOWED_HOSTS.
Bad Request: /download.jetbrains.com:443
"CONNECT download.jetbrains.com:443 HTTP/1.1" 400 66862
Watching for file changes with StatReloader
D:\GB\HTML CSS\FinishTask\pecipes\list_recipes\list_recipes\settings.py changed, reloading.
Watching for file changes with StatReloader
D:\GB\HTML CSS\FinishTask\pecipes\list_recipes\list_recipes\settings.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
"GET / HTTP/1.1" 200 11664
"GET /static/recipesapp/css/style.css HTTP/1.1" 404 1831
"GET /static/debug_toolbar/css/toolbar.css HTTP/1.1" 200 12621
"GET /static/debug_toolbar/css/print.css HTTP/1.1" 200 43
"GET /static/debug_toolbar/js/toolbar.js HTTP/1.1" 200 13578
"GET /static/debug_toolbar/js/utils.js HTTP/1.1" 200 4527
"GET /__debug__/render_panel/?store_id=8fa35432c2ab4c71a6380d627c1fc5b8&panel_id=StaticFilesPanel HTTP/1.1" 200 35747
Invalid HTTP_HOST header: 'download.jetbrains.com'. You may need to add 'download.jetbrains.com' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "C:\Users\dara3\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dara3\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\utils\deprecation.py", line 133, in __call__
    response = self.process_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dara3\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\middleware\common.py", line 48, in process_request
    host = request.get_host()
           ^^^^^^^^^^^^^^^^^^
  File "C:\Users\dara3\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\http\request.py", line 151, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'download.jetbrains.com'. You may need to add 'download.jetbrains.com' to ALLOWED_HOSTS.
Bad Request: /download.jetbrains.com:443
"CONNECT download.jetbrains.com:443 HTTP/1.1" 400 76844
"GET /__debug__/render_panel/?store_id=8fa35432c2ab4c71a6380d627c1fc5b8&panel_id=SignalsPanel HTTP/1.1" 200 2319
"GET /__debug__/render_panel/?store_id=8fa35432c2ab4c71a6380d627c1fc5b8&panel_id=VersionsPanel HTTP/1.1" 200 760
"GET /__debug__/render_panel/?store_id=8fa35432c2ab4c71a6380d627c1fc5b8&panel_id=SettingsPanel HTTP/1.1" 200 26477
"GET /__debug__/render_panel/?store_id=8fa35432c2ab4c71a6380d627c1fc5b8&panel_id=HistoryPanel HTTP/1.1" 200 4157
"GET /static/debug_toolbar/js/history.js HTTP/1.1" 200 3515
"GET /__debug__/history_refresh/?store_id=8fa35432c2ab4c71a6380d627c1fc5b8&exclude_history=True HTTP/1.1" 200 3370
"GET /__debug__/render_panel/?store_id=8fa35432c2ab4c71a6380d627c1fc5b8&panel_id=SQLPanel HTTP/1.1" 200 209908
Invalid HTTP_HOST header: 'download.jetbrains.com'. You may need to add 'download.jetbrains.com' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "C:\Users\dara3\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dara3\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\utils\deprecation.py", line 133, in __call__
    response = self.process_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dara3\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\middleware\common.py", line 48, in process_request
    host = request.get_host()
           ^^^^^^^^^^^^^^^^^^
  File "C:\Users\dara3\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\http\request.py", line 151, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'download.jetbrains.com'. You may need to add 'download.jetbrains.com' to ALLOWED_HOSTS.
Bad Request: /download.jetbrains.com:443
"CONNECT download.jetbrains.com:443 HTTP/1.1" 400 76843
"GET /__debug__/render_panel/?store_id=8fa35432c2ab4c71a6380d627c1fc5b8&panel_id=HeadersPanel HTTP/1.1" 200 5241
"GET /__debug__/render_panel/?store_id=8fa35432c2ab4c71a6380d627c1fc5b8&panel_id=TemplatesPanel HTTP/1.1" 200 6685
"GET /recipe_add/ HTTP/1.1" 302 0
"GET /login/ HTTP/1.1" 200 11100
"GET /static/recipesapp/css/style.css HTTP/1.1" 404 1831
"GET /login/ HTTP/1.1" 200 11034
"GET /static/recipesapp/css/style.css HTTP/1.1" 404 1831
"GET /recipe_search/ HTTP/1.1" 200 11273
"GET /static/recipesapp/css/style.css HTTP/1.1" 404 1831
"GET /recipes_all HTTP/1.1" 200 12457
"GET /static/recipesapp/css/style.css HTTP/1.1" 404 1831
"GET /recipe_show/1 HTTP/1.1" 200 21237
"GET /static/recipesapp/css/style.css HTTP/1.1" 404 1831
"GET /__debug__/render_panel/?store_id=ad9489a409054121881fcabbad9e522e&panel_id=StaticFilesPanel HTTP/1.1" 200 35747
"GET /__debug__/render_panel/?store_id=ad9489a409054121881fcabbad9e522e&panel_id=TemplatesPanel HTTP/1.1" 200 59332
"GET /__debug__/render_panel/?store_id=ad9489a409054121881fcabbad9e522e&panel_id=SignalsPanel HTTP/1.1" 200 2364
"GET / HTTP/1.1" 200 12091
"GET /static/recipesapp/css/style.css HTTP/1.1" 404 1831
"GET /__debug__/render_panel/?store_id=4a48f59a2f4549e593c275ff3411dd98&panel_id=ProfilingPanel HTTP/1.1" 200 62871
